---
# chdir: ...
# user: ...
environment: production
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 2048
max_persistent_conns: 128
require: []
wait: 30
socket: tmp/sockets/thin.socket
# address: 127.0.0.1
# port: 5000
servers: 2
daemonize: true
onebyone: true
threaded: true
threadpool_size: 16

